export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const ENSURE_REGISTRATION_SUCCESS = 'ENSURE_REGISTRATION_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCHING_DATA = "FETCHING_DATA"
export const SENT_STATUS = "SENT_STATUS"

